[global]
developmentMode = false
showWarningOnDirectExecution = false

[client]
showSidebarNavigation = true
showErrorDetails = false

[theme]
primaryColor = "#e1617bff"
backgroundColor = "#fac4c4ff"
secondaryBackgroundColor = "#f8b2b2ff"
textColor = "#1a283fff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

